function [net, info] = train(ytrain, Xtrain, Xval, labelsVal)
    layers = [ ...
        sequenceInputLayer(44)
        bilstmLayer(240, 'OutputMode', 'sequence')
        reluLayer
        dropoutLayer(0.2)
        bilstmLayer(240, 'OutputMode', 'sequence')
        reluLayer
        dropoutLayer(0.2)
        fullyConnectedLayer(4)
        softmaxLayer
        classificationLayer
    ];

    options = trainingOptions('adam', ...
        'MaxEpochs',6, ...
        'MiniBatchSize',50, ...
        'InitialLearnRate',0.01, ...
        'LearnRateDropPeriod',3, ...
        'LearnRateSchedule','piecewise', ...
        'GradientThreshold',1, ...
        'ValidationData', {Xval, labelsVal}, ...
        'ValidationFrequency',50, ...
        'ValidationPatience', 6, ...
        'Plots','training-progress',...
        'Verbose',1);
    
    [net, info] = trainNetwork(Xtrain,ytrain,layers,options);
end
