function net = train(frames, Xtrain, Xval, labelsVal)
    layers = [ ...
        sequenceInputLayer(44)
        lstmLayer(200,'OutputMode','sequence')
        dropoutLayer(0.2)
        fullyConnectedLayer(4)
        softmaxLayer
        classificationLayer
    ];

    options = trainingOptions('adam', ...
        'MaxEpochs',5, ...
        'MiniBatchSize',50, ...
        'InitialLearnRate',0.01, ...
        'LearnRateDropPeriod',3, ...
        'LearnRateSchedule','piecewise', ...
        'GradientThreshold',1, ...
        'ValidationData', {Xval, labelsVal}, ...
        'Plots','training-progress',...
        'Verbose',1);
    
    net = trainNetwork(Xtrain,frames.framedLabelsTrain,layers,options);
end
