function net = train(frames, fsstTrain, fsstVal, labelsVal)
        layers = [ ...
        sequenceInputLayer(44)
        lstmLayer(200,'OutputMode','sequence')
        fullyConnectedLayer(4)
        softmaxLayer
        classificationLayer];

    options = trainingOptions('adam', ...
        'MaxEpochs',5, ...
        'MiniBatchSize',50, ...
        'InitialLearnRate',0.01, ...
        'LearnRateDropPeriod',3, ...
        'LearnRateSchedule','piecewise', ...
        'GradientThreshold',1, ...
        'ValidationData', {fsstVal, labelsVal}, ...
        'Plots','training-progress',...
        'Verbose',1);
    
    net = trainNetwork(fsstTrain,frames.framedLabelsTrain,layers,options);
end
