@startuml
  start
    fork
      :Adquisición del PCG;
      :Filtro pasa-bajos;
      :Filtro pasa-altos;
      :Filtro de picos de fricción y media móvil;
    fork again
      :Adquisición del ECG;
      :Detección de la onda R y el fin de la onda T;
    end fork

    if (Entrenamiento o evaluación) then (Entrenamiento)
      fork
        :Hiperparámetros;
      fork again
        :Framing;
        :Extracción de FSST;
      fork again
        :Extracción del envelograma homomórfico;
        :Etiquetamiento del PCG;
      end fork
      :Entrenamiento de la red LSTM;
    else (Evaluación)
      :Framing;
      :Extracción de FSST;
      :Clasificación (Modelo LSTM entrenado);
    endif
  stop
@enduml
