function calculateMetrics(obj)
  obj.truePositiveRate()
  obj.trueNegativeRate()
  obj.positivePredictiveValue()
  obj.negativePredictiveValue()
  obj.falseNegativeRate()
  obj.falsePositiveRate()
  obj.falseDiscoveryRate()
  obj.falseOmissionRate()
  obj.accuracy()
  obj.f1Score()
  obj.matthewCorrelationCoefficient()
  obj.bookMakerInformedness()
  obj.markedness()
end